import PostForm from "@/components/PostForm";

interface PostEdit {
    params: {
        postId: string;
    }
}

export const metadata = {
  title: 'Edit Post',
  description: 'Edit Post Page Generated by Next.js',
}

export default function PostEditPage(props: PostEdit) {
    return (
        <>
            <header>
                <h1>PostEdit {props.params.postId} Page</h1>
            </header>
            <PostForm postId={props.params.postId}/>
        </>
    )
}