import PostForm from "@/components/PostForm";
import { getPost } from "@/services/posts.server";

interface PostEdit {
    params: {
        postId: string;
    }
}

export const metadata = {
  title: 'Edit Post',
  description: 'Edit Post Page Generated by Next.js',
}

export default async function PostEditPage(props: PostEdit) {
    const { postId } = props.params;
    const post = await getPost(postId);
    return (
        <>
            <header>
                <h1>PostEdit {postId} Page</h1>
            </header>
            <PostForm postId={postId} title={post.title} body={post.body}/>
        </>
    )
}