export const metadata = {
  title: 'About',
  description: 'About Page Generated by Next.js',
}

export default function AboutPage() {
    return (
        <>
            <header>
                <h1>About Page</h1>
            </header>
        </>
    )
}