
export const dynamic = "force-static";

export const metadata = {
  title: 'Home',
  description: 'Home Page Generated by Next.js',
}

export default function HomePage() {
    return (
        <>
            <header>
                <h1>Home Page</h1>
            </header>
        </>
    )
}